CREATE SCHEMA IF NOT EXISTS __SCHEMA__;

CREATE TABLE IF NOT EXISTS __SCHEMA__.fct_awc_monthly_snapshot (
    awc_code TEXT NOT NULL,
    period DATE NOT NULL,
    state_name TEXT,
    district_name TEXT,
    project_name TEXT,
    sector_name TEXT,
    awc_name TEXT,
    source_file TEXT NOT NULL,
    total_active_children_0_6_years DOUBLE PRECISION,
    total_active_children_measured_0_6_years DOUBLE PRECISION,
    measuring_efficiency_0_6_years_pct DOUBLE PRECISION,
    total_active_children_measured_0_5_years DOUBLE PRECISION,
    suw_count DOUBLE PRECISION,
    muw_count DOUBLE PRECISION,
    severely_stunted_count DOUBLE PRECISION,
    moderately_stunted_count DOUBLE PRECISION,
    sam_count DOUBLE PRECISION,
    mam_count DOUBLE PRECISION,
    suw_rate_pct DOUBLE PRECISION,
    sam_rate_pct DOUBLE PRECISION,
    mam_rate_pct DOUBLE PRECISION,
    stunting_rate_pct DOUBLE PRECISION,
    PRIMARY KEY (awc_code, period)
);

CREATE TABLE IF NOT EXISTS __SCHEMA__.fct_awc_anomaly_flags (
    awc_code TEXT NOT NULL,
    period DATE NOT NULL,
    metric_name TEXT NOT NULL,
    state_name TEXT,
    district_name TEXT,
    project_name TEXT,
    sector_name TEXT,
    awc_name TEXT,
    source_file TEXT NOT NULL,
    current_value DOUBLE PRECISION,
    previous_value DOUBLE PRECISION,
    delta_value DOUBLE PRECISION,
    absolute_delta_value DOUBLE PRECISION,
    rolling_baseline_value DOUBLE PRECISION,
    baseline_gap_value DOUBLE PRECISION,
    threshold_value DOUBLE PRECISION,
    flag_reason TEXT NOT NULL,
    PRIMARY KEY (awc_code, period, metric_name)
);

CREATE TABLE IF NOT EXISTS __SCHEMA__.fct_awc_risk_snapshot (
    awc_code TEXT NOT NULL,
    period DATE NOT NULL,
    state_name TEXT,
    district_name TEXT,
    project_name TEXT,
    sector_name TEXT,
    awc_name TEXT,
    source_file TEXT NOT NULL,
    measuring_efficiency_0_6_years_pct DOUBLE PRECISION,
    suw_rate_pct DOUBLE PRECISION,
    sam_rate_pct DOUBLE PRECISION,
    mam_rate_pct DOUBLE PRECISION,
    stunting_rate_pct DOUBLE PRECISION,
    risk_flags TEXT,
    risk_flag_count INTEGER NOT NULL,
    risk_level TEXT NOT NULL,
    PRIMARY KEY (awc_code, period)
);

CREATE TABLE IF NOT EXISTS __SCHEMA__.mart_awc_alerts_latest (
    awc_code TEXT PRIMARY KEY,
    current_period TEXT NOT NULL,
    previous_period TEXT,
    state_name TEXT,
    district_name TEXT,
    project_name TEXT,
    sector_name TEXT,
    awc_name TEXT,
    source_file TEXT NOT NULL,
    total_active_children_0_6_years DOUBLE PRECISION,
    previous_total_active_children_0_6_years DOUBLE PRECISION,
    delta_total_active_children_0_6_years DOUBLE PRECISION,
    total_active_children_measured_0_6_years DOUBLE PRECISION,
    previous_total_active_children_measured_0_6_years DOUBLE PRECISION,
    delta_total_active_children_measured_0_6_years DOUBLE PRECISION,
    measuring_efficiency_0_6_years_pct DOUBLE PRECISION,
    previous_measuring_efficiency_0_6_years_pct DOUBLE PRECISION,
    delta_measuring_efficiency_0_6_years_pct DOUBLE PRECISION,
    total_active_children_measured_0_5_years DOUBLE PRECISION,
    previous_total_active_children_measured_0_5_years DOUBLE PRECISION,
    delta_total_active_children_measured_0_5_years DOUBLE PRECISION,
    suw_count DOUBLE PRECISION,
    previous_suw_count DOUBLE PRECISION,
    delta_suw_count DOUBLE PRECISION,
    muw_count DOUBLE PRECISION,
    previous_muw_count DOUBLE PRECISION,
    delta_muw_count DOUBLE PRECISION,
    severely_stunted_count DOUBLE PRECISION,
    previous_severely_stunted_count DOUBLE PRECISION,
    delta_severely_stunted_count DOUBLE PRECISION,
    moderately_stunted_count DOUBLE PRECISION,
    previous_moderately_stunted_count DOUBLE PRECISION,
    delta_moderately_stunted_count DOUBLE PRECISION,
    sam_count DOUBLE PRECISION,
    previous_sam_count DOUBLE PRECISION,
    delta_sam_count DOUBLE PRECISION,
    mam_count DOUBLE PRECISION,
    previous_mam_count DOUBLE PRECISION,
    delta_mam_count DOUBLE PRECISION,
    suw_rate_pct DOUBLE PRECISION,
    previous_suw_rate_pct DOUBLE PRECISION,
    delta_suw_rate_pct DOUBLE PRECISION,
    sam_rate_pct DOUBLE PRECISION,
    previous_sam_rate_pct DOUBLE PRECISION,
    delta_sam_rate_pct DOUBLE PRECISION,
    mam_rate_pct DOUBLE PRECISION,
    previous_mam_rate_pct DOUBLE PRECISION,
    delta_mam_rate_pct DOUBLE PRECISION,
    stunting_rate_pct DOUBLE PRECISION,
    previous_stunting_rate_pct DOUBLE PRECISION,
    delta_stunting_rate_pct DOUBLE PRECISION,
    risk_level TEXT NOT NULL,
    risk_flags TEXT,
    risk_flag_count INTEGER NOT NULL,
    previous_risk_period TEXT,
    previous_risk_level TEXT,
    previous_risk_flags TEXT,
    previous_risk_flag_count INTEGER,
    risk_direction TEXT NOT NULL,
    recent_anomaly_count INTEGER NOT NULL,
    latest_anomaly_period TEXT,
    recent_anomaly_metrics TEXT,
    recent_flag_reasons TEXT,
    alert_scenario TEXT NOT NULL
);
