CREATE TABLE IF NOT EXISTS raw_awc_file_batches (
    batch_id VARCHAR(64) PRIMARY KEY,
    run_timestamp_utc TIMESTAMP NOT NULL,
    source_file_name VARCHAR(255) NOT NULL,
    source_period VARCHAR(7) NOT NULL,
    schema_type VARCHAR(32) NOT NULL,
    row_count INTEGER NOT NULL,
    column_count INTEGER NOT NULL,
    file_path VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS fct_awc_monthly_snapshot (
    awc_code VARCHAR(32) NOT NULL,
    period DATE NOT NULL,
    state_name VARCHAR(128),
    district_name VARCHAR(128),
    project_name VARCHAR(128),
    sector_name VARCHAR(128),
    awc_name VARCHAR(255),
    source_file VARCHAR(255) NOT NULL,
    total_active_children_0_6_years NUMERIC(18, 4),
    total_active_children_measured_0_6_years NUMERIC(18, 4),
    measuring_efficiency_0_6_years_pct NUMERIC(18, 4),
    total_active_children_measured_0_5_years NUMERIC(18, 4),
    suw_count NUMERIC(18, 4),
    muw_count NUMERIC(18, 4),
    severely_stunted_count NUMERIC(18, 4),
    moderately_stunted_count NUMERIC(18, 4),
    sam_count NUMERIC(18, 4),
    mam_count NUMERIC(18, 4),
    suw_rate_pct NUMERIC(18, 4),
    sam_rate_pct NUMERIC(18, 4),
    mam_rate_pct NUMERIC(18, 4),
    stunting_rate_pct NUMERIC(18, 4),
    PRIMARY KEY (awc_code, period)
);

CREATE TABLE IF NOT EXISTS fct_awc_anomaly_flags (
    awc_code VARCHAR(32) NOT NULL,
    period DATE NOT NULL,
    metric_name VARCHAR(128) NOT NULL,
    state_name VARCHAR(128),
    district_name VARCHAR(128),
    project_name VARCHAR(128),
    sector_name VARCHAR(128),
    awc_name VARCHAR(255),
    source_file VARCHAR(255) NOT NULL,
    current_value NUMERIC(18, 6),
    previous_value NUMERIC(18, 6),
    delta_value NUMERIC(18, 6),
    absolute_delta_value NUMERIC(18, 6),
    rolling_baseline_value NUMERIC(18, 6),
    baseline_gap_value NUMERIC(18, 6),
    threshold_value NUMERIC(18, 6),
    flag_reason VARCHAR(128) NOT NULL,
    PRIMARY KEY (awc_code, period, metric_name)
);

CREATE TABLE IF NOT EXISTS fct_awc_risk_snapshot (
    awc_code VARCHAR(32) NOT NULL,
    period DATE NOT NULL,
    state_name VARCHAR(128),
    district_name VARCHAR(128),
    project_name VARCHAR(128),
    sector_name VARCHAR(128),
    awc_name VARCHAR(255),
    source_file VARCHAR(255) NOT NULL,
    measuring_efficiency_0_6_years_pct NUMERIC(18, 4),
    suw_rate_pct NUMERIC(18, 4),
    sam_rate_pct NUMERIC(18, 4),
    mam_rate_pct NUMERIC(18, 4),
    stunting_rate_pct NUMERIC(18, 4),
    risk_flags VARCHAR(1024),
    risk_flag_count INTEGER NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    PRIMARY KEY (awc_code, period)
);

CREATE TABLE IF NOT EXISTS mart_awc_alerts_latest (
    awc_code VARCHAR(32) PRIMARY KEY,
    current_period VARCHAR(7) NOT NULL,
    previous_period VARCHAR(7),
    state_name VARCHAR(128),
    district_name VARCHAR(128),
    project_name VARCHAR(128),
    sector_name VARCHAR(128),
    awc_name VARCHAR(255),
    source_file VARCHAR(255) NOT NULL,
    total_active_children_0_6_years NUMERIC(18, 4),
    previous_total_active_children_0_6_years NUMERIC(18, 4),
    delta_total_active_children_0_6_years NUMERIC(18, 4),
    total_active_children_measured_0_6_years NUMERIC(18, 4),
    previous_total_active_children_measured_0_6_years NUMERIC(18, 4),
    delta_total_active_children_measured_0_6_years NUMERIC(18, 4),
    measuring_efficiency_0_6_years_pct NUMERIC(18, 4),
    previous_measuring_efficiency_0_6_years_pct NUMERIC(18, 4),
    delta_measuring_efficiency_0_6_years_pct NUMERIC(18, 4),
    total_active_children_measured_0_5_years NUMERIC(18, 4),
    previous_total_active_children_measured_0_5_years NUMERIC(18, 4),
    delta_total_active_children_measured_0_5_years NUMERIC(18, 4),
    suw_count NUMERIC(18, 4),
    previous_suw_count NUMERIC(18, 4),
    delta_suw_count NUMERIC(18, 4),
    muw_count NUMERIC(18, 4),
    previous_muw_count NUMERIC(18, 4),
    delta_muw_count NUMERIC(18, 4),
    severely_stunted_count NUMERIC(18, 4),
    previous_severely_stunted_count NUMERIC(18, 4),
    delta_severely_stunted_count NUMERIC(18, 4),
    moderately_stunted_count NUMERIC(18, 4),
    previous_moderately_stunted_count NUMERIC(18, 4),
    delta_moderately_stunted_count NUMERIC(18, 4),
    sam_count NUMERIC(18, 4),
    previous_sam_count NUMERIC(18, 4),
    delta_sam_count NUMERIC(18, 4),
    mam_count NUMERIC(18, 4),
    previous_mam_count NUMERIC(18, 4),
    delta_mam_count NUMERIC(18, 4),
    suw_rate_pct NUMERIC(18, 4),
    previous_suw_rate_pct NUMERIC(18, 4),
    delta_suw_rate_pct NUMERIC(18, 4),
    sam_rate_pct NUMERIC(18, 4),
    previous_sam_rate_pct NUMERIC(18, 4),
    delta_sam_rate_pct NUMERIC(18, 4),
    mam_rate_pct NUMERIC(18, 4),
    previous_mam_rate_pct NUMERIC(18, 4),
    delta_mam_rate_pct NUMERIC(18, 4),
    stunting_rate_pct NUMERIC(18, 4),
    previous_stunting_rate_pct NUMERIC(18, 4),
    delta_stunting_rate_pct NUMERIC(18, 4),
    risk_level VARCHAR(16) NOT NULL,
    risk_flags VARCHAR(1024),
    risk_flag_count INTEGER NOT NULL,
    previous_risk_period VARCHAR(7),
    previous_risk_level VARCHAR(16),
    previous_risk_flags VARCHAR(1024),
    previous_risk_flag_count INTEGER,
    risk_direction VARCHAR(16) NOT NULL,
    recent_anomaly_count INTEGER NOT NULL,
    latest_anomaly_period VARCHAR(7),
    recent_anomaly_metrics VARCHAR(1024),
    recent_flag_reasons VARCHAR(1024),
    alert_scenario VARCHAR(64) NOT NULL
);
